#:import menu menu


MainWidget:

<MainWidget>:
    canvas.before: 
        Rectangle:
            size: self.size
            source: 'images/bg1.jpg'
    menu_widget: menu_widget
    perspectiive_point_x: self.width/2
    perspectiive_point_y: self.height*0.75
    MenuWidget: 
        id: menu_widget
    Label:
        text: root.score_txt
        font_size: dp(20)
        font_name: 'fonts/Eurostile.ttf'
        size_hint: .18, .2
        pos_hint: {"x": 0, "top": 1} 